# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  voicebyauribusapi:
    image: voicebyauribusapi
    build:
      context: .
      dockerfile: VoiceByAuribus.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5037:5037
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
