using VoiceByAuribus_API.Features.WebhookSubscriptions.Domain;

namespace VoiceByAuribus_API.Features.WebhookSubscriptions.Application.Dtos;

/// <summary>
/// DTO for creating a new webhook subscription.
/// The secret will be automatically generated by the system.
/// </summary>
public class CreateWebhookSubscriptionDto
{
    /// <summary>
    /// Gets or sets the HTTPS URL where webhook notifications will be sent.
    /// </summary>
    public required string Url { get; set; }

    /// <summary>
    /// Gets or sets an optional description for this webhook subscription.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Gets or sets the events to subscribe to.
    /// Defaults to all events (ConversionCompleted, ConversionFailed).
    /// </summary>
    public WebhookEvent[] Events { get; set; } = [
        WebhookEvent.ConversionCompleted,
        WebhookEvent.ConversionFailed
    ];
}
